export const products = [
  {
    id: 1,
    title: "cuadro gato",
    price: 35000,
    stock: 5,
    description: "cuadro de un gato en blanco y negro",
    category: "cuadros blanco y negro",
    imageUrl: "",
  },
  {
    id: 1,
    title: "cuadro Positano",
    price: 42000,
    stock: 3,
    description: "cuadro paisaje de Positano, Italia",
    category: "cuadros de paisajes",
    imageUrl: "",
  },
  {
    id: 1,
    title: "cuadro autos",
    price: 23000,
    stock: 15,
    description: "cuadro infantil de autos",
    category: "cuadros infantiles",
    imageUrl: "",
  },
  {
    id: 1,
    title: "cuadro arcoiris",
    price: 18000,
    stock: 8,
    description: "cuadro infantil de arcoiris",
    category: "cuadros infantiles",
    imageUrl: "",
  },
];
